### ISSUE TITLE
Issue with valid card number (according to Luhn) but unknown vendor

### ISSUE THREAD

**Issue by intrueder** [Serhii92/Test_Task#2]
Vendor for `35301113333000001` has been recognized as `Unknown` (correct, 17 digits instead of 16 for JCB)
Such number should not pass validation, but it passes.

**Comment by Serhii92** [comment]
Fixed #1, #2. Also I've found issue in my implementation of GenerateNextCreditCardVendor with numbers which has a lot of "0" and fixed it.

According to credit card structure it contains the first 6 digits which are the Issuer Identification Number. It will identify the institution that issued the credit card. The remaining digits are the person’s account number (7th and following excluding last digits).
So from the business point of view it seems that next credit card number should have the same IIN(first 6 digits) as entered one and only account number should be incremented. So I've implemented GenerateNextCreditCard according to this approach,

But I'm not sure is it correct so I added another function GenerateNext which doesn't take into account IIN and generates next valid number with the same vendor. 

Could you please clarify which approach should have been implemented? And then I'll remove unnecessary one. Thanks)
